image: node:current

services:
  - docker:stable-dind

variables:
  DOCKER_REGISTRY: registry.gitlab.com

cache:
  key: $CI_PROJECT_PATH_SLUG
  paths:
    - node_modules/

stages:
  - prepare
  - test
  - deploy

make-build-env:
  stage: prepare
  image: docker:stable
  variables:
    DOCKER_IMAGE: $DOCKER_REGISTRY/$CI_PROJECT_PATH/build-env:latest
  script:
    - echo "Building $DOCKER_IMAGE"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
    - docker build -t $DOCKER_IMAGE -f ci/Dockerfile.build-env .
    - docker push $DOCKER_IMAGE

test:
  stage: test
  script:
    - npm install
    - npm test -- --coverage

sast:
  stage: test
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}"
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code
  artifacts:
    reports:
      sast: gl-sast-report.json

pages:
  image: $DOCKER_REGISTRY/$CI_PROJECT_PATH/build-env:latest
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv public public-original
    - mv build public
    # Make precompressed gzip versions of files
    - find public -type f -iregex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -execdir gzip -f --keep {} \;
  artifacts:
    paths:
      - public
  only:
    - master
